image: docker:stable
services:
  - docker:stable-dind

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  - apk add --no-cache jq

build-master:
  stage: build
  script:
    - |
      # Get latest version
      KCPTUN_VERSION=$(curl -sS https://api.github.com/repos/xtaci/kcptun/releases/latest | jq -cre '.tag_name | ltrimstr("v")')
      # Debug
      echo "Version: ${KCPTUN_VERSION}"
    # Build
    - docker build --pull --build-arg KCPTUN_VERSION=${KCPTUN_VERSION} -t "${CI_REGISTRY_IMAGE}" .
    - docker tag "${CI_REGISTRY_IMAGE}" "${CI_REGISTRY_IMAGE}:${KCPTUN_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  except:
    - master
