# Variables
variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

get_version:
  stage: .pre
  image: alpine:edge
  before_script:
    - apk add --no-cache -U jq curl
  script:
    - |
      # Get latest version
      KCPTUN_BRANCH=$(curl -sS https://api.github.com/repos/xtaci/kcptun/releases/latest | jq -cre '.tag_name')
      # Debug
      echo "Version: ${KCPTUN_BRANCH}"
      echo -n "${KCPTUN_BRANCH}" > .version
  artifacts:
    paths:
      - .version

.build-image:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    KCPTUN_BRANCH: "master"
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}

build-master:
  extends: .build-image
  script:
    # Master tag
    - docker build --pull --build-arg KCPTUN_BRANCH=${KCPTUN_BRANCH} -t "${CI_REGISTRY_IMAGE}:${KCPTUN_BRANCH}" .
    - docker push "${CI_REGISTRY_IMAGE}:${KCPTUN_BRANCH}"
  only:
    - master

build-stable:
  extends: .build-image
  needs:
    - get_version
  script:
    - export KCPTUN_BRANCH=$(cat .version)
    # Latest tag
    - docker build --pull --build-arg KCPTUN_BRANCH=${KCPTUN_BRANCH} -t "${CI_REGISTRY_IMAGE}" .
    - docker push "${CI_REGISTRY_IMAGE}"
    # Version tag
    - docker tag "${CI_REGISTRY_IMAGE}" "${CI_REGISTRY_IMAGE}:${KCPTUN_BRANCH}"
    - docker push "${CI_REGISTRY_IMAGE}:${KCPTUN_BRANCH}"
  only:
    - master

build:
  extends: .build-image
  script:
    # Git SHA tag
    - docker build --pull --build-arg KCPTUN_BRANCH=${KCPTUN_BRANCH} -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  except:
    - master
