# Variables
variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

get_version:
  stage: .pre
  image: alpine:edge
  before_script:
    - apk add --no-cache -U jq curl
  script:
    - |
      # Get latest version
      KCPTUN_VERSION=$(curl -sS https://api.github.com/repos/xtaci/kcptun/releases/latest | jq -cre '.tag_name | ltrimstr("v")')
      # Debug
      echo "Version: ${KCPTUN_VERSION}"
      echo -n "${KCPTUN_VERSION}" > .version
  artifacts:
    paths:
      - .version

.build-image:
  stage: build
  needs:
    - get_version
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - export KCPTUN_VERSION=$(cat .version)
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}

build-master:
  extends: .build-image
  script:
    - docker build --pull --build-arg KCPTUN_VERSION=${KCPTUN_VERSION} -t "${CI_REGISTRY_IMAGE}" .
    - docker push "${CI_REGISTRY_IMAGE}"
    - docker tag "${CI_REGISTRY_IMAGE}" "${CI_REGISTRY_IMAGE}:${KCPTUN_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}:${KCPTUN_VERSION}"
  only:
    - master

build:
  extends: .build-image
  script:
    - docker build --pull --build-arg KCPTUN_VERSION=${KCPTUN_VERSION} -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  except:
    - master
