#!/bin/bash

# Get latest version
KCPTUN_VERSION=$(curl -sS https://api.github.com/repos/xtaci/kcptun/releases/latest | grep tag_name | cut -d\" -f4 | tr -d "v")

# Debug
echo "Version: ${KCPTUN_VERSION}"

# Build
docker build --pull --build-arg KCPTUN_VERSION=${KCPTUN_VERSION} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
